shop_example:
  target: dev
  outputs:
    dev:
      dbname: rushil-daya
      host: localhost
      pass: postgres
      port: 5432
      schema: shop
      threads: 1
      type: postgres
      user: postgres
    ci_cd:
      dbname: rushil-daya
      host: localhost
      pass: postgres
      port: 5432
      schema: shop
      threads: 1
      type: postgres
      user: postgres
    prd:
      type: bigquery
      method: oauth
      project: rushil-daya
      dataset: shop
      threads: 1