# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    name: Continuous Integration of the endpoint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Display something useless as a first step
      run: |
        echo "Hello World automated from the PR pipeline !"

    - name: Setup
      working-directory: shop_example
      run: |
        docker-compose up -d
    
    - name: Install dbt
      working-directory: shop_example
      run: |
        pip install -r ../requirements.txt
        dbt deps

    - name: Run dbt tests
      working-directory: shop_example
      run: |
        dbt run --target ci_cd
        dbt test --target ci_cd

    - id: "auth"
      uses: "google-github-actions/auth@v1"
      with:
        credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

    - name: "Set up Cloud SDK"
      uses: "google-github-actions/setup-gcloud@v1"

    - name: "Use gcloud CLI"
      run: "gcloud info"
